version: '3.8'

services:
  autenticacionlogin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autenticacionlogin
    ports:
      - "3003:3000"  # Mapea el puerto 3000 del contenedor al 3003 en la máquina anfitriona
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET} 
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=MoneyTracker
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
