version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: MoneyTracker
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped

  autenticacionlogin:
    build:
      context: ./Authentication_Login
      dockerfile: Dockerfile
    container_name: autenticacionlogin
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=MoneyTracker
    env_file:
      - ./Authentication_Login/.env
    volumes:
      - ./Authentication_Login:/usr/src/app
    restart: unless-stopped
    networks:
      - backend

  apipagos:
    build:
      context: ./apipagos
      dockerfile: Dockerfile
    container_name: apipagos
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=MoneyTracker
    env_file:
      - ./apipagos/.env
    volumes:
      - ./apipagos:/usr/src/app
    restart: unless-stopped
    networks:
      - backend

  apinotas:
    build: 
      context: ./apinotas
      dockerfile: Dockerfile
    container_name: apinotas
    ports:
      - "3004:3000" 
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=MoneyTracker
    env_file: 
      - ./apinotas/.env
    volumes:
      - ./apinotas:/usr/src/app
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
